### ISSUE TITLE
Deprecated (8192): explode(): Passing null to parameter #2 ($string) of type string is deprecated in [stackify/logger/src/Stackify/Log/Entities/Api/WebRequestDetail.php, line 332]

### ISSUE THREAD

**Issue by rajesh-kumawat** [stackify/stackify-api-php#24]
In Php8 - we see this issue.

**Comment by homiedopie** [comment]
Hi @rajesh-kumawat - Thank you for reporting the issue! I added a comment on your PR (#25) and see if you can resolve that and we can move forward.
